"use client";

import { useState, useEffect } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { FadeIn } from "@/components/animations/fade-in";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { apiClient } from "@/lib/api/client";
import { PaginatedAlerts, AlertRead } from "@/lib/api/types/alert";
import { useConfig } from "@/lib/api/config";
import { parseSeverityFromTitle } from "@/lib/api/adapters";
import { AlertCard } from "@/components/alerts/alert-card";
import { AlertDetailPanel } from "@/components/alerts/alert-detail-panel";
import { ShieldAlert, Loader2, Filter } from "lucide-react";
import { Counter } from "@/components/animations/counter";

/**
 * Derive severity from the alert — works in both demo and real modes.
 * In demo mode, __mock_meta is available.
 * In real mode, severity is parsed from the auto-generated title.
 */
function getAlertSeverity(alert: AlertRead & { __mock_meta?: any }): string {
  return alert.__mock_meta?.severity || parseSeverityFromTitle(alert.title);
}

export default function AlertsPage() {
  const { isDemoMode } = useConfig();
  
  const [alerts, setAlerts] = useState<(AlertRead & { __mock_meta?: any })[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedAlert, setSelectedAlert] = useState<(AlertRead & { __mock_meta?: any }) | null>(null);
  
  // Filters
  const [statusFilter, setStatusFilter] = useState<"all" | "active" | "acknowledged" | "resolved">("all");
  const [severityFilter, setSeverityFilter] = useState<"all" | "critical" | "high">("all");

  const fetchAlerts = async () => {
    setLoading(true);
    try {
      const res = await apiClient<PaginatedAlerts>("/alerts");
      setAlerts(res.items as any);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAlerts();
  }, []);

  // Derive severity using the unified getter (works for both demo and real modes)
  const activeCritical = alerts.filter(a => a.status === "active" && getAlertSeverity(a) === "critical").length;
  const activeHigh = alerts.filter(a => a.status === "active" && getAlertSeverity(a) === "high").length;
  const totalUnresolved = alerts.filter(a => a.status !== "resolved" && a.status !== "dismissed").length;

  const filteredAlerts = alerts.filter(a => {
    if (statusFilter !== "all" && a.status !== statusFilter) return false;
    if (severityFilter !== "all" && getAlertSeverity(a) !== severityFilter) return false;
    return true;
  });

  return (
    <AppShell>
      <div className="fixed inset-0 pointer-events-none z-[-1] opacity-20">
        <div className="absolute top-[-20%] right-[-10%] w-[50%] h-[50%] bg-danger/20 blur-[150px] rounded-full mix-blend-screen" />
      </div>

      <FadeIn direction="up">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 py-4 mb-8 border-b border-border/50 pb-6">
          <div>
            <div className="flex items-center space-x-3 mb-2">
              <h1 className="text-3xl md:text-4xl font-bold tracking-tight text-foreground">
                Alert Center
              </h1>
              {isDemoMode && <Badge variant="warning">SIMULATION MODE</Badge>}
            </div>
            <p className="text-foreground/60 text-base max-w-2xl">
              Monitor and manage disaster risk warnings generated by the DisasterSense intelligence system.
            </p>
          </div>
        </div>
      </FadeIn>

      {/* Summary Cards */}
      <FadeIn delay={0.1}>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          <div className="bg-surface-muted/30 border border-critical/30 rounded-xl p-6 flex flex-col relative overflow-hidden">
             <div className="absolute top-0 right-0 p-4 opacity-10"><ShieldAlert className="w-16 h-16 text-critical" /></div>
             <span className="text-sm font-semibold text-critical uppercase tracking-wider mb-2">Active Critical</span>
             <span className="text-4xl font-bold"><Counter to={activeCritical} /></span>
          </div>
          <div className="bg-surface-muted/30 border border-danger/30 rounded-xl p-6 flex flex-col relative overflow-hidden">
             <div className="absolute top-0 right-0 p-4 opacity-10"><ShieldAlert className="w-16 h-16 text-danger" /></div>
             <span className="text-sm font-semibold text-danger uppercase tracking-wider mb-2">Active High</span>
             <span className="text-4xl font-bold"><Counter to={activeHigh} /></span>
          </div>
          <div className="bg-surface-muted/30 border border-white/10 rounded-xl p-6 flex flex-col relative overflow-hidden">
             <span className="text-sm font-semibold text-foreground/50 uppercase tracking-wider mb-2">Total Unresolved</span>
             <span className="text-4xl font-bold"><Counter to={totalUnresolved} /></span>
          </div>
        </div>
      </FadeIn>

      {/* Filters & Feed */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
        
        {/* Filters Sidebar */}
        <div className="lg:col-span-1">
          <FadeIn delay={0.2} className="sticky top-24 space-y-6">
             <div className="bg-surface-muted/20 border border-white/5 rounded-xl p-5">
               <h3 className="text-sm font-semibold uppercase tracking-wider text-foreground/50 mb-4 flex items-center">
                 <Filter className="w-4 h-4 mr-2" /> Filters
               </h3>
               
               <div className="space-y-4">
                 <div>
                   <label className="text-xs text-foreground/40 uppercase mb-2 block">Status</label>
                   <div className="flex flex-col space-y-2">
                     {["all", "active", "acknowledged", "resolved"].map((s) => (
                       <Button 
                         key={s} 
                         variant={statusFilter === s ? "default" : "outline"}
                         size="sm"
                         className="justify-start capitalize"
                         onClick={() => setStatusFilter(s as any)}
                       >
                         {s}
                       </Button>
                     ))}
                   </div>
                 </div>

                 <div>
                   <label className="text-xs text-foreground/40 uppercase mb-2 block">Severity</label>
                   <div className="flex flex-col space-y-2">
                     {["all", "critical", "high"].map((s) => (
                       <Button 
                         key={s} 
                         variant={severityFilter === s ? "default" : "outline"}
                         size="sm"
                         className="justify-start capitalize"
                         onClick={() => setSeverityFilter(s as any)}
                       >
                         {s}
                       </Button>
                     ))}
                   </div>
                 </div>
               </div>
             </div>
          </FadeIn>
        </div>

        {/* Feed */}
        <div className="lg:col-span-3">
          <FadeIn delay={0.3}>
            {loading ? (
              <div className="py-20 flex flex-col items-center justify-center text-foreground/40">
                <Loader2 className="w-8 h-8 animate-spin mb-4" />
                <span>Loading Alerts...</span>
              </div>
            ) : filteredAlerts.length === 0 ? (
              <div className="py-20 flex flex-col items-center justify-center text-foreground/40 bg-surface-muted/10 rounded-xl border border-dashed border-white/10">
                <ShieldAlert className="w-12 h-12 mb-4 opacity-20" />
                <span>No alerts match the current filters.</span>
              </div>
            ) : (
              <div className="space-y-4">
                {filteredAlerts.map(alert => (
                  <div key={alert.id} onClick={() => setSelectedAlert(alert)} className="cursor-pointer transition-transform hover:scale-[1.01]">
                    <AlertCard 
                      title={alert.title}
                      message={alert.message}
                      severity={getAlertSeverity(alert) as "info" | "warning" | "critical" | "high"}
                      time={new Date(alert.created_at).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}
                    />
                  </div>
                ))}
              </div>
            )}
          </FadeIn>
        </div>

      </div>

      <AlertDetailPanel 
        alert={selectedAlert} 
        open={!!selectedAlert} 
        onClose={() => setSelectedAlert(null)}
        onStatusChange={() => {
          // Re-fetch alerts after a status change action
          fetchAlerts();
        }}
      />
    </AppShell>
  );
}
