"""
Alert service — business logic for CRUD and lifecycle operations on Alert records.
"""

from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import select, func
from sqlalchemy.orm import Session

from app.models.alert import Alert, AlertStatus, AlertAudit
from app.schemas.alert import AlertCreate, AlertAcknowledge, AlertRespond, AlertNoteCreate


def _log_audit(db: Session, alert_id: int, actor: str, action: str, note: Optional[str] = None):
    audit = AlertAudit(alert_id=alert_id, actor=actor, action=action, note=note)
    db.add(audit)
    db.commit()


def create_alert(db: Session, data: AlertCreate) -> Alert:
    """Insert a new Alert record with status ACTIVE."""
    alert = Alert(**data.model_dump(), status=AlertStatus.ACTIVE)
    db.add(alert)
    db.commit()
    db.refresh(alert)
    _log_audit(db, alert.id, "SYSTEM", "DETECTED", note="Alert automatically generated by RiskEngine.")
    return alert


def get_alert(db: Session, alert_id: int) -> Optional[Alert]:
    """Fetch a single Alert by primary key, or None."""
    return db.get(Alert, alert_id)


def list_alerts(
    db: Session,
    *,
    skip: int = 0,
    limit: int = 50,
    status: Optional[AlertStatus] = None,
    location_id: Optional[int] = None,
    disaster_event_id: Optional[int] = None,
) -> tuple[list[Alert], int]:
    """
    Return a paginated, filtered list of alerts.

    Returns (items, total_count).
    """
    query = select(Alert)

    if status is not None:
        query = query.where(Alert.status == status)
    if location_id is not None:
        query = query.where(Alert.location_id == location_id)
    if disaster_event_id is not None:
        query = query.where(Alert.disaster_event_id == disaster_event_id)

    count_query = select(func.count()).select_from(query.subquery())
    total = db.execute(count_query).scalar_one()

    query = query.order_by(Alert.created_at.desc()).offset(skip).limit(limit)
    items = list(db.execute(query).scalars().all())

    return items, total


def acknowledge_alert(
    db: Session, alert: Alert, data: AlertAcknowledge, actor: str
) -> Alert:
    """Mark an alert as acknowledged by a named operator."""
    if alert.status != AlertStatus.ACTIVE:
        raise ValueError(f"Cannot acknowledge alert from state {alert.status}")
    alert.status = AlertStatus.ACKNOWLEDGED
    alert.acknowledged_by = data.acknowledged_by
    alert.acknowledged_at = datetime.now(timezone.utc)
    db.commit()
    db.refresh(alert)
    _log_audit(db, alert.id, actor, "ACKNOWLEDGED", note=f"Acknowledged by {data.acknowledged_by}")
    return alert


def respond_alert(db: Session, alert: Alert, data: AlertRespond) -> Alert:
    """Mark an alert as response_in_progress."""
    if alert.status != AlertStatus.ACKNOWLEDGED:
        raise ValueError(f"Cannot begin response from state {alert.status}")
    alert.status = AlertStatus.RESPONSE_IN_PROGRESS
    db.commit()
    db.refresh(alert)
    _log_audit(db, alert.id, data.actor, "RESPONSE_STARTED", note=data.note)
    return alert


def add_alert_note(db: Session, alert: Alert, data: AlertNoteCreate) -> Alert:
    """Add a note without changing status."""
    if alert.status not in (AlertStatus.ACKNOWLEDGED, AlertStatus.RESPONSE_IN_PROGRESS):
        raise ValueError(f"Cannot add response notes in state {alert.status}")
    _log_audit(db, alert.id, data.actor, "NOTE_ADDED", note=data.note)
    db.refresh(alert)
    return alert


def resolve_alert(db: Session, alert: Alert, actor: str) -> Alert:
    """Mark an alert as resolved."""
    if alert.status not in (AlertStatus.ACTIVE, AlertStatus.ACKNOWLEDGED, AlertStatus.RESPONSE_IN_PROGRESS):
        raise ValueError(f"Cannot resolve alert from state {alert.status}")
    alert.status = AlertStatus.RESOLVED
    alert.resolved_at = datetime.now(timezone.utc)
    db.commit()
    db.refresh(alert)
    _log_audit(db, alert.id, actor, "RESOLVED", note="Incident resolved.")
    return alert


def dismiss_alert(db: Session, alert: Alert, actor: str) -> Alert:
    """Mark an alert as dismissed."""
    if alert.status in (AlertStatus.RESOLVED, AlertStatus.DISMISSED):
         raise ValueError(f"Cannot dismiss alert from state {alert.status}")
    alert.status = AlertStatus.DISMISSED
    db.commit()
    db.refresh(alert)
    _log_audit(db, alert.id, actor, "DISMISSED", note="Alert dismissed without resolution.")
    return alert


def update_alert(db: Session, alert: Alert, updates: dict) -> Alert:
    """Apply partial updates to an Alert record."""
    for field, value in updates.items():
        setattr(alert, field, value)
    db.commit()
    db.refresh(alert)
    return alert


def delete_alert(db: Session, alert: Alert) -> None:
    """Delete an Alert record."""
    db.delete(alert)
    db.commit()
