"""Add MLFeedback model

Revision ID: 9c4d7ff4c148
Revises: 48fcf700e41c
Create Date: 2026-09-16 14:34:44.915300+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c4d7ff4c148'
down_revision: Union[str, Sequence[str], None] = '48fcf700e41c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('hazard_type', sa.String(length=50), nullable=False),
    sa.Column('feedback_type', sa.Enum('confirmed_event', 'false_positive', 'false_negative', 'uncertain', 'data_correction', name='feedbacktype'), nullable=False),
    sa.Column('review_status', sa.Enum('submitted', 'under_review', 'accepted', 'rejected', 'approved_ground_truth', name='reviewstatus'), nullable=False),
    sa.Column('observed_outcome', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('feature_snapshot', sa.Text(), nullable=True),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['disaster_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_feedback_event_id'), 'ml_feedback', ['event_id'], unique=False)
    op.create_index(op.f('ix_ml_feedback_id'), 'ml_feedback', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_feedback_id'), table_name='ml_feedback')
    op.drop_index(op.f('ix_ml_feedback_event_id'), table_name='ml_feedback')
    op.drop_table('ml_feedback')
    # ### end Alembic commands ###
