"""add_record_type_provenance

Revision ID: 98ef58a27a52
Revises: 1e358e15ae59
Create Date: 2026-09-15 18:56:40.329485+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ef58a27a52'
down_revision: Union[str, Sequence[str], None] = '1e358e15ae59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    record_type_enum = sa.Enum('HISTORICAL', 'PREDICTIVE', 'DEMO', name='recordtype')
    record_type_enum.create(op.get_bind())
    op.add_column('disaster_events', sa.Column('record_type', record_type_enum, nullable=False, server_default='PREDICTIVE'))
    op.add_column('disaster_events', sa.Column('source_reference', sa.String(length=500), nullable=True))
    op.create_index('ix_disaster_events_record_type', 'disaster_events', ['record_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_disaster_events_record_type', table_name='disaster_events')
    op.drop_column('disaster_events', 'source_reference')
    op.drop_column('disaster_events', 'record_type')
    sa.Enum(name='recordtype').drop(op.get_bind())
    # ### end Alembic commands ###
