"""Add Candidate and Audit models

Revision ID: 526c8006fbfa
Revises: 9c4d7ff4c148
Create Date: 2026-09-16 14:43:01.753933+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '526c8006fbfa'
down_revision: Union[str, Sequence[str], None] = '9c4d7ff4c148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.String(length=100), nullable=False),
    sa.Column('hazard_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready_for_offline_evaluation', 'archived', name='candidatestatus'), nullable=False),
    sa.Column('feature_schema', sa.Text(), nullable=False),
    sa.Column('geographic_coverage', sa.String(length=255), nullable=True),
    sa.Column('temporal_coverage', sa.String(length=255), nullable=True),
    sa.Column('methodology', sa.Text(), nullable=True),
    sa.Column('exclusions', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_candidates_id'), 'dataset_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_dataset_candidates_version_name'), 'dataset_candidates', ['version_name'], unique=True)
    op.create_table('candidate_feedback_link',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['dataset_candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feedback_id'], ['ml_feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_id', 'feedback_id')
    )
    op.create_table('ml_governance_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('previous_state', sa.String(length=50), nullable=True),
    sa.Column('new_state', sa.String(length=50), nullable=True),
    sa.Column('decision', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['dataset_candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['feedback_id'], ['ml_feedback.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_governance_audits_id'), 'ml_governance_audits', ['id'], unique=False)
    op.add_column('ml_feedback', sa.Column('evidence_type', sa.String(length=100), nullable=True))
    op.add_column('ml_feedback', sa.Column('evidence_reference', sa.String(length=500), nullable=True))
    op.add_column('ml_feedback', sa.Column('exclusion_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ml_feedback', 'exclusion_reason')
    op.drop_column('ml_feedback', 'evidence_reference')
    op.drop_column('ml_feedback', 'evidence_type')
    op.drop_index(op.f('ix_ml_governance_audits_id'), table_name='ml_governance_audits')
    op.drop_table('ml_governance_audits')
    op.drop_table('candidate_feedback_link')
    op.drop_index(op.f('ix_dataset_candidates_version_name'), table_name='dataset_candidates')
    op.drop_index(op.f('ix_dataset_candidates_id'), table_name='dataset_candidates')
    op.drop_table('dataset_candidates')
    # ### end Alembic commands ###
