"""Add emergency resources table

Revision ID: 48fcf700e41c
Revises: 38ab9ca98b87
Create Date: 2026-09-16 04:09:06.419153+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '48fcf700e41c'
down_revision: Union[str, Sequence[str], None] = '38ab9ca98b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.Enum('SHELTER', 'HOSPITAL', 'FIRE_STATION', 'POLICE_STATION', 'RELIEF_CENTER', 'OTHER_EMERGENCY_RESOURCE', name='resourcetype'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_reference', sa.String(length=512), nullable=True),
    sa.Column('record_type', postgresql.ENUM('HISTORICAL', 'PREDICTIVE', 'DEMO', name='recordtype', create_type=False), nullable=False),
    sa.Column('verification_status', sa.Enum('VERIFIED', 'UNVERIFIED', name='verificationstatus'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('contact_info', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_resources_district'), 'emergency_resources', ['district'], unique=False)
    op.create_index(op.f('ix_emergency_resources_id'), 'emergency_resources', ['id'], unique=False)
    op.create_index('ix_emergency_resources_lat_lon', 'emergency_resources', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_emergency_resources_name'), 'emergency_resources', ['name'], unique=False)
    op.create_index(op.f('ix_emergency_resources_resource_type'), 'emergency_resources', ['resource_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emergency_resources_resource_type'), table_name='emergency_resources')
    op.drop_index(op.f('ix_emergency_resources_name'), table_name='emergency_resources')
    op.drop_index('ix_emergency_resources_lat_lon', table_name='emergency_resources')
    op.drop_index(op.f('ix_emergency_resources_id'), table_name='emergency_resources')
    op.drop_index(op.f('ix_emergency_resources_district'), table_name='emergency_resources')
    op.drop_table('emergency_resources')
    # ### end Alembic commands ###
