"""Add notifications and user preferences

Revision ID: 7798b33bc69f
Revises: 002
Create Date: 2026-09-15 17:59:12.468085+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7798b33bc69f'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', name='notificationchannel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'NOT_CONFIGURED', name='deliverystatus'), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_alert_user_channel', 'notification_deliveries', ['alert_id', 'user_id', 'channel'], unique=True)
    op.create_index(op.f('ix_notification_deliveries_alert_id'), 'notification_deliveries', ['alert_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_id'), 'notification_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_user_id'), 'notification_deliveries', ['user_id'], unique=False)
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('email_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('sms_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sms_enabled')
    op.drop_column('users', 'email_enabled')
    op.drop_column('users', 'phone_number')
    op.drop_index(op.f('ix_notification_deliveries_user_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_alert_id'), table_name='notification_deliveries')
    op.drop_index('ix_notification_alert_user_channel', table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    # ### end Alembic commands ###
