"""Update notification deliveries schema

Revision ID: 1e358e15ae59
Revises: 7798b33bc69f
Create Date: 2026-09-15 18:37:38.814100+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e358e15ae59'
down_revision: Union[str, Sequence[str], None] = '7798b33bc69f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_deliveries', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_notification_alert_user_channel'), table_name='notification_deliveries')
    op.create_index('ix_notification_alert_user_channel', 'notification_deliveries', ['alert_id', 'user_id', 'channel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_alert_user_channel', table_name='notification_deliveries')
    op.create_index(op.f('ix_notification_alert_user_channel'), 'notification_deliveries', ['alert_id', 'user_id', 'channel'], unique=True)
    op.drop_column('notification_deliveries', 'retry_count')
    # ### end Alembic commands ###
